# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#191716'
foreground='#daba8b'
cursor='#8c4f4a'

# Colors
color0='#0f0e0d'
color1='#845336'
color2='#57553c'
color3='#a17e3e'
color4='#43454f'
color5='#604848'
color6='#5c6652'
color7='#a18b62'
color8='#383332'
color9='#8c4f4a'
color10='#898471'
color11='#c8b491'
color12='#65788f'
color13='#755e4a'
color14='#718062'
color15='#bc9d66'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
