# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#000000'
foreground='#ffffff'
cursor='#eb4509'

# Colors
color0='#251f1f'
color1='#eb4509'
color2='#94e76b'
color3='#ffac18'
color4='#46aede'
color5='#e32c57'
color6='#d6dbac'
color7='#efefef'
color8='#5e5e5e'
color9='#eb4509'
color10='#94e76b'
color11='#ffac18'
color12='#46aede'
color13='#e32c57'
color14='#d6dbac'
color15='#efefef'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
