--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#2b2b2b"
foreground="#e6e1dc"
cursor="#e6e1dc"

-- Colors
color0="#2b2b2b"
color1="#da4939"
color2="#a5c261"
color3="#ffc66d"
color4="#6d9cbe"
color5="#b6b3eb"
color6="#519f50"
color7="#e6e1dc"
color8="#5a647e"
color9="#da4939"
color10="#a5c261"
color11="#ffc66d"
color12="#6d9cbe"
color13="#b6b3eb"
color14="#519f50"
color15="#f9f7f3"
