# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#222222'
foreground='#e6e3c6'
cursor='#ce3b2b'

# Colors
color0='#151515'
color1='#a3291b'
color2='#7a961b'
color3='#cc880e'
color4='#485664'
color5='#5f7a5f'
color6='#7a88a3'
color7='#e6e3c6'
color8='#3e3c3a'
color9='#ce3b2b'
color10='#7a961b'
color11='#ffad19'
color12='#5d6d7d'
color13='#7c9d7c'
color14='#9baccd'
color15='#EEEEEC'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
