--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#1F1F1F"
foreground="#C0B18B"
cursor="#D17B49"

-- Colors
color0="#4A3637"
color1="#D17B49"
color2="#7B8748"
color3="#AF865A"
color4="#535C5C"
color5="#775759"
color6="#6D715E"
color7="#C0B18B"
color8="#785f60"
color9="#D17B49"
color10="#7B8748"
color11="#AF865A"
color12="#535C5C"
color13="#775759"
color14="#6D715E"
color15="#C0B18B"
