#! /bin/sh

numlockx on &
pkill sxhkd
sxhkd &

# Workspace settings
external_monitor_status=$(xrandr --query | grep 'HDMI-1-2')
case "$external_monitor_status" in
  *disconnected*) 
	bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 8 9 10
	;;
  *) 
	#bspc monitor eDP-1-1 -d 1 2 3 4 5 
	bspc monitor eDP-1-1 -d 1 2 3 4 5
	bspc monitor HDMI-1-2 -d 6 7 8 9 10 
	#bspc monitor HDMI-1-2 -d 6 7 8 9 10
	;;
esac

bspc config border_width		1
bspc config window_gap			3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle 		 true
bspc config pointer_follows_monitor	true

bspc rule -a qutebrowser state=floating
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a zathura state=tiled
bspc rule --add scratchpad sticky=true
setxkbmap -option caps:super

# Use the default cursor
xsetroot -cursor_name left_ptr &

# Run applications
tmux new-session -d -s protonbridge protonmail-bridge -c &
dunst &
autorandr -c &
feh --bg-fill ~/.config/wallpapers/current &
wal -Rq
$HOME/.config/polybar/launch.sh $
picom --config ~/.config/picom/picom.conf &
xsetwacom --set "Wacom Bamboo One S Pen stylus" MapToOutput 1920x1080+0+0

# Pywal colors
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color1"

#wmname LG3D
