#! /bin/sh

# unmap caps lock
numlockx on &
setxkbmap -option caps:super

pkill sxhkd
sxhkd &

# Monitor config
# PRIMARY_MONITOR="eDP-1-1"
# SECONDARY_MONITOR="HDMI-1-2"
PRIMARY_MONITOR="eDP1" # Hybrid monitors
SECONDARY_MONITOR="HDMI2"

# Workspace settings
external_monitor_status=$(xrandr --query | grep $SECONDARY_MONITOR)
case "$external_monitor_status" in
  *disconnected*) 
	bspc monitor $PRIMARY_MONITOR -d 1 2 3 4 5 6 7 8 9 10
	;;
  *) 
	bspc monitor $PRIMARY_MONITOR -d 1 2 3 4 5
	bspc monitor $SECONDARY_MONITOR -d 6 7 8 9 10 
	;;
esac

# bspc settings
bspc config border_width		1
bspc config window_gap			3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle 		 true
bspc config pointer_follows_monitor	true

bspc rule -a qutebrowser state=floating
bspc rule -a Zathura state=tiled
bspc rule --add scratchpad sticky=true

# Use the default x cursor
xsetroot -cursor_name left_ptr &

# Run applications
tmux new-session -d -s protonbridge protonmail-bridge -c &
dunst &
#autorandr -c &
feh --bg-fill ~/.config/wallpapers/current &
wal -Rq
$HOME/.config/polybar/launch.sh $
picom --config ~/.config/picom/picom.conf &
xsetwacom --set "Wacom Bamboo One S Pen stylus" MapToOutput 1920x1080+0+0

# colors
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color1"
