--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#1a1a1a"
foreground="#d8d8d8"
cursor="#d8d8d8"

-- Colors
color0="#1a1a1a"
color1="#ab4642"
color2="#a1b56c"
color3="#f7ca88"
color4="#7cafc2"
color5="#ba8baf"
color6="#86c1b9"
color7="#d8d8d8"
color8="#585858"
color9="#ab4642"
color10="#a1b56c"
color11="#f7ca88"
color12="#7cafc2"
color13="#ba8baf"
color14="#86c1b9"
color15="#f8f8f8"
