# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#1a1a1a'
foreground='#856237'
cursor='#ccbaad'

# Colors
color0='#1a1a1a'
color1='#6b4747'
color2='#8d7138'
color3='#856237'
color4='#3c3c49'
color5='#3c342e'
color6='#5d5a4b'
color7='#ccbaad'
color8='#4a4a4a'
color9='#6b4747'
color10='#8d7138'
color11='#856237'
color12='#3c3c49'
color13='#3c342e'
color14='#5d5a4b'
color15='#eae2dc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
