# Shell variables
# Generated by 'wal'
wallpaper='/home/magnias/.config/wallpapers/current'

# Special
background='#1a1b1b'
foreground='#c5c6c6'
cursor='#c5c6c6'

# Colors
color0='#1a1b1b'
color1='#366a7f'
color2='#407e95'
color3='#ae4a4c'
color4='#5098b3'
color5='#a7ba5e'
color6='#91cfb9'
color7='#c5c6c6'
color8='#535454'
color9='#366a7f'
color10='#407e95'
color11='#ae4a4c'
color12='#5098b3'
color13='#a7ba5e'
color14='#91cfb9'
color15='#c5c6c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
