--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#1a1a1a"
foreground="#c8a168"
cursor="#312e30"

-- Colors
color0="#1a1a1a"
color1="#ab6d4e"
color2="#88885d"
color3="#c8a168"
color4="#45626e"
color5="#7c5545"
color6="#456e66"
color7="#c3b495"
color8="#c3b495"
color9="#ab6d4e"
color10="#88885d"
color11="#c8a168"
color12="#45626e"
color13="#7c5545"
color14="#456e66"
color15="#c3b495"
