# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#1a1a1a'
foreground='#d8d8d8'
cursor='#d8d8d8'

# Colors
color0='#1a1a1a'
color1='#ab4642'
color2='#a1b56c'
color3='#f7ca88'
color4='#7cafc2'
color5='#ba8baf'
color6='#86c1b9'
color7='#d8d8d8'
color8='#585858'
color9='#ab4642'
color10='#a1b56c'
color11='#f7ca88'
color12='#7cafc2'
color13='#ba8baf'
color14='#86c1b9'
color15='#f8f8f8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
