--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/magnias/.config/wallpapers/current"

-- Special
background="#050E1B"
foreground="#7ec5c2"
cursor="#7ec5c2"

-- Colors
color0="#050E1B"
color1="#1A6768"
color2="#4E5646"
color3="#1D9374"
color4="#B19565"
color5="#056C8A"
color6="#557487"
color7="#7ec5c2"
color8="#588987"
color9="#1A6768"
color10="#4E5646"
color11="#1D9374"
color12="#B19565"
color13="#056C8A"
color14="#557487"
color15="#7ec5c2"
